compatibility_date = "2021-10-18"
name = "mastercard-backbank-dev"
type = "javascript" # webpack
account_id = "9ddca7c9df604668fc6d14f079b2f066"
workers_dev = true
# webpack_config = "webpack.config.js"
[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
exclude = ["node_modules","*"]
include = ["dist/index.js","src/index.js"]
name = "mastercard-backbank"

[env.staging]
name = "mastercard-backbank-staging"

[build]
command = "npx parcel build src/index.js"
upload.format = "service-worker"
upload.dir = "dist/worker"
upload.main = "dist/worker/index.js"
