compatibility_date = "2021-10-18"
name = "mastercard-backbank-dev"
type = "javascript" # webpack
account_id = "9ddca7c9df604668fc6d14f079b2f066"
workers_dev = true #if using default subdomain, here: api ok
# webpack_config = "webpack.config.js"
route = "" #if not using default subdomain, here: api not needed, defaults err
zone_id = "" #if not using default subdomain, here: api not needed
# [site]
# bucket = "./dist"
# entry-point = "workers-site"

[env.production]
# exclude = ["node_modules","*"]
# include = ["dist/*","src/*"]
name = "mastercard-backbank"

[env.staging]
name = "mastercard-backbank-staging"

# [build.upload.rules]
# type = "CommonJS"
# globs = ["**/*.js", "**/*.cjs"]
[build.upload]
format = "modules" # "service-workers"
# dir = "dist"
main = "./shim.mjs"
[build]
# command = "npx browserify src/index.js > src/index.js && npx parcel build src/index.js"
command = "npm install && npm run build"
# command = "npx parcel build src/index.js"
# command = "node build.js"
# command = "npx rollup src/index.js --file dist/index.js --format es"

[durable_objects]
bindings = [{ name = "EXAMPLE_CLASS", class_name = "DurableObjectExample" }]
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DurableObjectExample"]
