compatibility_date = "2021-10-18"
name = "mastercard-backbank-dev"
type = "javascript" # webpack
account_id = "9ddca7c9df604668fc6d14f079b2f066"
workers_dev = true
# webpack_config = "webpack.config.js"
[site]
bucket = "./index.js"
entry-point = "workers-site"

[env.production]
name = "mastercard-backbank"

[env.staging]
name = "mastercard-backbank-staging"

[build]
include = ["src","index.js"]
command = "parcel src/index.js"
